# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_UI_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox,QMainWindow
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_txt.setGeometry(QtCore.QRect(130, 30, 521, 341))
        self.file_txt.setObjectName("file_txt")
        self.file_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.file_dir.setGeometry(QtCore.QRect(100, 390, 281, 21))
        self.file_dir.setObjectName("file_dir")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(380, 360, 261, 51))
        self.widget.setObjectName("widget")
        self.close_file = QtWidgets.QPushButton(self.widget)
        self.close_file.setGeometry(QtCore.QRect(180, 20, 75, 23))
        self.close_file.setObjectName("close_file")
        self.read_file = QtWidgets.QPushButton(self.widget)
        self.read_file.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.read_file.setObjectName("read_file")
        self.save_file = QtWidgets.QPushButton(self.widget)
        self.save_file.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.save_file.setObjectName("save_file")
        self.files_addr = QtWidgets.QLabel(self.centralwidget)
        self.files_addr.setGeometry(QtCore.QRect(40, 390, 61, 20))
        self.files_addr.setObjectName("files_addr")
        self.histry = QtWidgets.QListWidget(self.centralwidget)
        self.histry.setGeometry(QtCore.QRect(10, 30, 111, 341))
        self.histry.setObjectName("histry")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.file_txt, self.histry)
        MainWindow.setTabOrder(self.histry, self.file_dir)
        MainWindow.setTabOrder(self.file_dir, self.read_file)
        MainWindow.setTabOrder(self.read_file, self.save_file)
        MainWindow.setTabOrder(self.save_file, self.close_file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close_file.setText(_translate("MainWindow", "关闭文件"))
        self.read_file.setText(_translate("MainWindow", "读取文件"))
        self.save_file.setText(_translate("MainWindow", "保存文件"))
        self.files_addr.setText(_translate("MainWindow", "文件位置："))
    def readfile(self,filename):
        def show_file_not_found_message():
            app = QApplication(sys.argv)
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("文件不存在")
            msg.setWindowTitle("错误")
            msg.exec_()
        import os.path
        if os.path.exists(filename):
            with open(filename,"r") as file:
                return file.readlines()
        else:
            show_file_not_found_message()
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

if __name__ == "__main__":
    app =  QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(app.exec_())
